dev.md as in dd-ingest-flow
DANS-KNAW/dd-transfer-to-vault pull request #39
Opened 2023-07-31 13:02 UTC by jo-pol

Fixes DD-

# Description of changes

# How to test

# Related PRs

(Add links)

*

# Notify

@DANS-KNAW/dataversedans

2023-07-31 13:06 UTC, jo-pol commented on docs/dev.md
> +This page contains information for developers about how to contribute to this project.
Copied from https://dans-knaw.github.io/dd-ingest-flow/dev/ but the intention looks broader than the content in both situations.

2023-07-31 13:25 UTC, ericdevries commented on docs/dev.md
> +start-hsqldb-server.sh
This is `start-hsqldb.sh`

2023-07-31 14:48 UTC, jo-pol commented on docs/dev.md
> +start-hsqldb-server.sh
no more since 11 Januari

2023-07-31 14:48 UTC, jo-pol commented on docs/dev.md
> +(not copy) a deposit (such as a zip of `src/test/resources/bags`) into `inboxes` configured in
copy-paste devil

2023-08-08 07:27 UTC, janvanmansum requested changes
Part of of the file describes generic stuff that we would need to repeat in each microservice's dev.md. We'll have to find a more efficient way of documenting that in the future; for now it is OK.

Some suggested improvements, see comments.

2023-08-08 07:27 UTC, janvanmansum commented on docs/dev.md
> +### Environment
```suggestion
### Initialize development environment
```

2023-08-08 07:27 UTC, janvanmansum commented on docs/dev.md
> +Open a separate terminal tab for `dd-transfer-to-vault` and one for its dependency `dd-vault-catalog` and run:
```suggestion
This is only necessary once per project. If you execute this any existing configuration and data will be reset.

Open a separate terminal tab for `dd-transfer-to-vault` and one for its dependency `dd-vault-catalog` and in each one run:
```

2023-08-08 07:27 UTC, janvanmansum commented on docs/dev.md
> +
Why not set the DB port to 9002 in one of the two project's `config.yml` and `db.properties`?

2023-08-09 06:28 UTC, merged